# Generated by Django 5.0.7 on 2024-07-23 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0002_alter_sitecontent_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitecontent",
            options={
                "verbose_name": "Site Content",
                "verbose_name_plural": "Site Contents",
            },
        ),
    ]
