# Generated by Django 5.0.7 on 2024-07-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("bot_token", models.CharField(max_length=255)),
                (
                    "bot_username",
                    models.CharField(blank=True, max_length=125, null=True),
                ),
            ],
            options={
                "verbose_name": "Telegram Bot",
                "verbose_name_plural": "Telegram Bots",
                "db_table": "telegram_bots",
            },
        ),
    ]
